let document = {
  title: '',
  rating: '',
  address: '',
  application: '',
  input0: "'AI-2' 4P 100A lockable isolator",
  input1: "Outside area of R/F Chiller Plant Room",
  input2: "'MCB-13' 4P 80A AC MCB",
  input3: "Outside area of R/F Chiller Plant Room",
  input4: "'PV System' 3P 100A AC MCCB",
  input5: "3.4.2",
  input6: "",
  checked1: false,
  checked2: false,
  currentRating: '',
  contact: '',
  phase: '',
  phoneNumber: '',
  list: {
    antiIslandingtime: {
      label: 'Anti-islanding time',
      width: 300,
      height: 200,
      data: [
        { index: 0, title: 'Phase L1', img: '', symbol: 'ms', value: '' },
        { index: 1, title: 'Phase L2', img: '', symbol: 'ms', value: '' },
        { index: 2, title: 'Phase L3', img: '', symbol: 'ms', value: '' }
      ]
    },
    TotalHarmonicCurrentDistortion: {
      label: 'Total Harmonic Current Distortion (should not exceed 5%)',
      width: 300,
      height: 200,
      data: [
        { index: 0, title: 'Phase L1', img: '', symbol: '%', value: '' },
        { index: 1, title: 'Phase L2', img: '', symbol: '%', value: '' },
        { index: 2, title: 'Phase L3', img: '', symbol: '%', value: '' }
      ]
    },
    Earthfault: {
      width: 300,
      height: 200,
      label: 'Earth fault loop impedance (should comply with EMSD’s CoP)',
      data: [
        { index: 0, title: 'Phase L1', img: '', symbol: 'Ω', value: '' },
        { index: 1, title: 'Phase L2', img: '', symbol: 'Ω', value: '' },
        { index: 2, title: 'Phase L3', img: '', symbol: 'Ω', value: '' }
      ]
    },   
    LineToNeutral: {
      width: 300,
      height: 200,
      label: 'Line to neutral loop impedance ',
      data: [
        { index: 0, title: 'Phase L1', img: '', symbol: 'Ω', value: '' },
        { index: 1, title: 'Phase L2', img: '', symbol: 'Ω', value: '' },
        { index: 2, title: 'Phase L3', img: '', symbol: 'Ω', value: '' }
      ]
    },  
    triptime: {
      width: 300,
      height: 200,
      label: 'RCD/RCBO trip time(if applicable)   ',
      data: [
        { index: 0, title: 'Phase L1', img: '', symbol: 'ms', value: '' },
        { index: 1, title: 'Phase L2', img: '', symbol: 'ms', value: '' },
        { index: 2, title: 'Phase L3', img: '', symbol: 'ms', value: '' }
      ]
    },  
    threePointOne : {
      label: '3.1 Overview of RE equipment (e.g. PV Panels, Wind Turbine & etc) and RE equipment inside Plantroom (e.g. Inverter, switchgear & etc)',
      data: [
        { index: 0, title: '', img: '', value: 'PV Panels'},
        { index: 1, title: '', img: '', value: 'Overview Of Equipment'},
        { index: 2, title: '', img: '', value: ''},
        { index: 3, title: '', img: '', value: ''},
        { index: 2, title: '', img: '', value: ''},
        { index: 3, title: '', img: '', value: ''},
        { index: 2, title: '', img: '', value: ''},
        { index: 3, title: '', img: '', value: ''},
      ]
    }, 
    threePointTwo : {
      label: '3.2 Nameplate, Technical Data Plate & Installation of RE equipment (e.g. Inverter, isolation transformer & etc)',
      data: [
        { index: 0, title: '', img: '', value: 'PV Panels'},
        { index: 1, title: '', img: '', value: 'Inverter'},
        { index: 2, title: '', img: '', value: '', symbol: 'kVA'},
        { index: 3, title: '', img: '', value: 'DC Panel'},
        { index: 4, title: '', img: '', value: ''},
        { index: 5, title: '', img: '', value: ''},
        { index: 6, title: '', img: '', value: ''},
        { index: 7, title: '', img: '', value: ''},
        { index: 8, title: '', img: '', value: ''},
        { index: 9, title: '', img: '', value: ''},
        { index: 10, title: '', img: '', value: ''},
        { index: 11, title: '', img: '', value: ''},
      ]
    }, 
    threepointThree: {
      label: '3.3 - Earthing Connection of RE equipment',
      data: [
        { 
          index: 0, 
          title: '', 
          options: [
            'PV Panels Metallic Frame to PV Panels Metallic Frame',
            'PV Panels Metallic Frame to PV Panels Metallic Supporting Frame',
            'PV Panels Metallic Supporting Frame to Earthing Terminal'
          ],
          select: '',
          img: ''
        },
        { 
          index: 1, 
          title: '', 
          options: [
            'PV Panels Metallic Frame to PV Panels Metallic Frame',
            'PV Panels Metallic Frame to PV Panels Metallic Supporting Frame',
            'PV Panels Metallic Supporting Frame to Earthing Terminal'
          ],
          select: '',
          img: ''
        },
        { 
          index: 2, 
          title: '', 
          options: [
            'PV Panels Metallic Frame to PV Panels Metallic Frame',
            'PV Panels Metallic Frame to PV Panels Metallic Supporting Frame',
            'PV Panels Metallic Supporting Frame to Earthing Terminal'
          ],
          select: '',
          img: ''
        },
        { 
          index: 3, 
          title: '', 
          img: '',
          value: 'Tx Earthing on Primary Neutral'
        },
      ]
    },
    threePointFour: {
      label: '3.4 DC warning labels at all DC Switchgear & panel and rating of all DC switchgears (Cont’d)',
      data: [
        { index: 2, 
          title: 'Please attach the PV Schematicand add cloud mark indication for DC warning labels at DC switchgear/DC switchgears’ metal box and attach their photos with description on the next page.', 
          img: '',
          width: 900,
          height: 800
        },        
        { 
          index: 0, 
          title: '', 
          options: [
            'Panel Name: ',
            'DC Switchgear Name & Rating: '
          ],
          select: '',
          value: '',
          img: '',
          appendTitle: '3.4 DC warning labels at all DC Switchgear & panel and rating of all DC switchgears (Cont’d)'
        },
        { 
          index: 1, 
          title: '', 
          options: [
            'Panel Name: ',
            'DC Switchgear Name & Rating: '
          ],
          select: '',
          value: '',
          img: ''
        },
        { 
          index: 1, 
          title: '',
          options: [
            'Panel Name: ',
            'DC Switchgear Name & Rating: '
          ],
          select: '',
          value: '', 
          img: ''
        },
        { 
          index: 1, 
          title: '', 
          options: [
            'Panel Name: ',
            'DC Switchgear Name & Rating: '
          ],
          select: '',
          value: '',
          img: ''
        },
        { index: 2, 
          title: '', 
          img: '', 
          value: '',
          select: '',
          options: ['Panel Name: ','DC Switchgear Name & Rating: '],
        },
        { index: 3, title: '', img: '', 
          value: ''},
        { index: 4, 
          title: '', 
          img: '', 
          value: '',
          select: '',
          options: ['Panel Name: ','DC Switchgear Name & Rating: '],
        },
        { index: 5, 
          title: '', 
          img: '', 
          value: '',
          select: '',
          options: ['Panel Name: ','DC Switchgear Name & Rating: '],          
        },
        { index: 6, 
          title: '', 
          img: '', 
          value: '',
          select: '',
          options: ['Panel Name: ','DC Switchgear Name & Rating: '],          
        },
        { index: 6, 
          title: '', 
          img: '', 
          value: '',
          select: '',
          options: ['Panel Name: ','DC Switchgear Name & Rating: '],
        },
        { index: 6, 
          title: '', 
          img: '', 
          value: '',
          select: '',
          options: ['Panel Name: ','DC Switchgear Name & Rating: '],
        },
        { index: 6, 
          title: '', 
          img: '', 
          value: '',
          select: '',
          options: ['Panel Name: ','DC Switchgear Name & Rating: '],
        },
        { index: 6, 
          title: '', 
          img: '', 
          value: '',
          select: '',
          options: ['Panel Name: ','DC Switchgear Name & Rating: '],
        },
        { index: 6, 
          title: '', 
          img: '', 
          value: '',
          select: '',
          options: ['Panel Name: ','DC Switchgear Name & Rating: '],
        },
        { index: 6, 
          title: '', 
          img: '', 
          value: '',
          select: '',
          options: ['Panel Name: ','DC Switchgear Name & Rating: '],
        },
        { index: 6, 
          title: '', 
          img: '', 
          value: '',
          select: '',
          options: ['Panel Name: ','DC Switchgear Name & Rating: '],
        },
      ]
    },
    // 不需要sample图
    threePointFive: {
      label: '3.5 AC dual source power supply warning labels at all AC switchgear & panel and rating of all AC switchgears (along the path from RE system to CLP’s power infeed) (Cont’d)',
      options: [
        'Panel Name:',
        'AC Switchgear Name & Rating:'
      ],
      data: [
        {
          width: 900,
          height: 800,
          index: 0, 
          title: 'Please attach the <span class="fw600">PV Schematic</span> and add cloud mark indication for AC dual source power supply warning labels at all AC switchgear & panel and attach their photos with description on the next page.', 
          img: ''
        },
        {
          index: 0, 
          title: 'Please attach the <span class="fw600">Main Electrical Schematic</span> and add cloud mark indication for AC dual source power supply warning labels at all AC switchgear & panel and attach their photos with description on the next page.', 
          img: '',
          width: 900,
          height: 800,
        },
        { 
          appendTitle: '3.5 AC dual source power supply warning labels at all AC switchgear & panel and rating of all AC switchgears (along the path from RE system to CLP’s power infeed) (Cont’d)',
          index: 0, 
          title: '', 
          img: '', 
          select: '', 
          value: '',
          options: [
            'Panel Name:',
            'AC Switchgear Name & Rating:'
          ],
        },
        { index: 1, 
          title: '', 
          img: '', 
          select: '', 
          value: '',
          options: [
            'Panel Name:',
            'AC Switchgear Name & Rating:'
          ],
        },
        { index: 1, 
          title: '', 
          img: '', 
          select: '', 
          value: '',
          options: [
            'Panel Name:',
            'AC Switchgear Name & Rating:'
          ],
        },
        { index: 1, 
          title: '', 
          img: '', 
          select: '', 
          value: '',
          options: ['Panel Name:','AC Switchgear Name & Rating:'],
        },
        { index: 1, 
          title: '', 
          img: '', 
          select: '', 
          value: '',
          options: ['Panel Name:','AC Switchgear Name & Rating:'],
        },
        { index: 1, 
          title: '', 
          img: '', 
          select: '', 
          value: '',
          options: ['Panel Name:','AC Switchgear Name & Rating:'],
        },
        { index: 1, 
          title: '', 
          img: '', 
          select: '', 
          value: '',
          options: ['Panel Name:','AC Switchgear Name & Rating:'],
        },
        { index: 1, 
          title: '', 
          img: '', 
          select: '', 
          value: '',
          options: ['Panel Name:','AC Switchgear Name & Rating:'],
        },
        { index: 1, 
          title: '', 
          img: '', 
          select: '', 
          value: '',
          options: ['Panel Name:','AC Switchgear Name & Rating:'],
        },
        { index: 1, 
          title: '', 
          img: '', 
          select: '', 
          value: '',
          options: ['Panel Name:','AC Switchgear Name & Rating:'],
        },
        { index: 1, 
          title: '', 
          img: '', 
          select: '', 
          value: '',
          options: ['Panel Name:','AC Switchgear Name & Rating:'],
        },
        { index: 1, 
          title: '', 
          img: '', 
          select: '', 
          value: '',
          options: ['Panel Name:','AC Switchgear Name & Rating:'],
        },
        { index: 1, 
          title: '', 
          img: '', 
          select: '', 
          value: '',
          options: ['Panel Name:','AC Switchgear Name & Rating:'],
        },
        { index: 1, 
          title: '', 
          img: '', 
          select: '', 
          value: '',
          options: ['Panel Name:','AC Switchgear Name & Rating:'],
        },
        { index: 1, 
          title: '', 
          img: '', 
          select: '', 
          value: '',
          options: ['Panel Name:','AC Switchgear Name & Rating:'],
        },
        { index: 1, 
          title: '', 
          img: '', 
          select: '', 
          value: '',
          options: ['Panel Name:','AC Switchgear Name & Rating:'],
        },
        { index: 1, 
          title: '', 
          img: '', 
          select: '', 
          value: '',
          options: ['Panel Name:','AC Switchgear Name & Rating:'],
        },
        { index: 1, 
          title: '', 
          img: '', 
          select: '', 
          value: '',
          options: ['Panel Name:','AC Switchgear Name & Rating:'],
        },
        { index: 1, 
          title: '', 
          img: '', 
          select: '', 
          value: '',
          options: ['Panel Name:','AC Switchgear Name & Rating:'],
        },
        { index: 1, 
          title: '', 
          img: '', 
          select: '', 
          value: '',
          options: ['Panel Name:','AC Switchgear Name & Rating:'],
        },
        { index: 1, 
          title: '', 
          img: '', 
          select: '', 
          value: '',
          options: ['Panel Name:','AC Switchgear Name & Rating:'],
        },
        { index: 1, 
          title: '', 
          img: '', 
          select: '', 
          value: '',
          options: ['Panel Name:','AC Switchgear Name & Rating:'],
        },
        { index: 1, 
          title: '', 
          img: '', 
          select: '', 
          value: '',
          options: ['Panel Name:','AC Switchgear Name & Rating:'],
        },
        { index: 1, 
          title: '', 
          img: '', 
          select: '', 
          value: '',
          options: ['Panel Name:','AC Switchgear Name & Rating:'],
        },
      ]
    },
    // 四个格子，前两个格子是option，后两个是input，不需要sample图，
    threePointSix: {
      label: '3.6 PV Schematics & Main Electrical Schematic Diagram (with cloud mark of RE System) in Plant Rooms',
      data: [
        { index: 0, 
          title: '', 
          options: ['PV Schematics', 'Main Schematics'],
          select: '',
          img: ''
        },
        { index: 1, 
          title: '', 
          options: ['PV Schematics', 'Main Schematics'],
          select: '',
          img: ''},
        { index: 1, 
          title: '', 
          value: '',
          img: ''},
        { index: 1, 
          title: '', 
          value: '',
          img: ''},
      ]
    },
    // 四个格子，都是option + value
    threePointSeven: {
      label: '3.7 FiT/RE Meter Location, Meter Board’s dimension & Cable Terminations',
      data: [
        { index: 0, 
          title: '',
          options: ['Overview of Meter Location', 'Meter Board Dimension','Cable Terminations'],
          select: '',
          value: '',
          img: ''
        },
        { index: 1, 
          title: '', 
          img: '',
          options: ['Overview of Meter Location', 'Meter Board Dimension','Cable Terminations'],
          select: '',
          value: '',
        },
        { index: 1, 
          title: '', 
          img: '',
          options: ['Overview of Meter Location', 'Meter Board Dimension','Cable Terminations'],
          select: '',
          value: '',
        },
        { index: 1, 
          title: '', 
          img: '',
          options: ['Overview of Meter Location', 'Meter Board Dimension','Cable Terminations'],
          select: '',
          value: '',
        },        
      ]
    },
    // 四个格子，都是option + value
    threePointEight: {
      label: "3.8 CLP's Revenue Meter & Substation",
      data: [
        { index: 0, 
          title: '', 
          options: ["CLP's Revenue Meter No:", "CLP's Substation No:"],
          select: '',
          value: '',
          img: ''
        },
        { index: 0, 
          title: '', 
          options: ["CLP's Revenue Meter No:", "CLP's Substation No:"],
          select: '',
          value: '',
          img: ''
        },
        { index: 0, 
          title: '', 
          options: ["CLP's Revenue Meter No:", "CLP's Substation No:"],
          select: '',
          value: '',
          img: ''
        },
        { index: 0, 
          title: '', 
          options: ["CLP's Revenue Meter No:", "CLP's Substation No:"],
          select: '',
          value: '',
          img: ''
        },
      ]
    },
    // 两个格子，都是value
    partFour: {
      label: "Part 4 Other Related Information (e.g. other related RE system or special information)",
      data: [
        { index: 0, title: '', img: '', value: 'Signal Strength'},
        { index: 1, title: '', img: '', value: 'REC Notice'},
      ]
    }
  }
}

export default document